#!/bin/bash
# ============================================================
# Biomni First Boot Initialization Script
# MySQL/Redis via docker-compose
# Spring Boot / Agent via systemd
# ============================================================

set -euo pipefail

LOCK_FILE="/opt/biomni/.initialized"
LOG_FILE="/opt/biomni/logs/first-boot.log"
CONFIG_DIR="/opt/biomni/config"
DOCKER_DIR="/opt/biomni/docker"
CRED_FILE="/home/ubuntu/biomni-credentials.txt"

if [ -f "$LOCK_FILE" ]; then
    echo "Biomni already initialized. Skipping."
    exit 0
fi

mkdir -p /opt/biomni/logs
exec > >(tee -a "$LOG_FILE") 2>&1
echo "=========================================="
echo "Biomni First Boot - $(date)"
echo "=========================================="

# ------------------------------------------
# 1. Generate secrets
# ------------------------------------------
echo "[1/5] Generating secrets..."

MYSQL_ROOT_PASSWORD="$(openssl rand -hex 24)"
BIOMNI_JWT_SECRET="$(openssl rand -hex 32)"

TOKEN=$(curl -sf -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 300" --connect-timeout 3 || echo "")
if [ -n "$TOKEN" ]; then
    INSTANCE_ID=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
      http://169.254.169.254/latest/meta-data/instance-id || echo "unknown")
    PUBLIC_IP=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
      http://169.254.169.254/latest/meta-data/public-ipv4 || echo "127.0.0.1")
else
    INSTANCE_ID="unknown"
    PUBLIC_IP="127.0.0.1"
fi

echo "  Instance: $INSTANCE_ID | Public IP: $PUBLIC_IP"

# ------------------------------------------
# 2. Write config files
# ------------------------------------------
echo "[2/5] Writing config files..."

# docker-compose .env (MySQL password)
cat > ${DOCKER_DIR}/.env <<ENVEOF
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENVEOF
chmod 600 ${DOCKER_DIR}/.env

# biomni.env (Spring Boot + Agent shared)
cat > ${CONFIG_DIR}/biomni.env <<ENVEOF
# Generated by first-boot.sh at $(date)

# Spring Boot
SPRING_PROFILES_ACTIVE=ami
SERVER_PORT=9999
SPRING_DATASOURCE_MYSQL_JDBC_URL=jdbc:mysql://127.0.0.1:3306/biomni?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
SPRING_DATASOURCE_MYSQL_USERNAME=root
SPRING_DATASOURCE_MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
SPRING_DATASOURCE_MYSQL_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
JWT_SECRET=${BIOMNI_JWT_SECRET}
JWT_EXPIRATION=86400000
SPRING_DATA_REDIS_HOST=127.0.0.1
SPRING_DATA_REDIS_PORT=6379

# Agent
JWT_SECRET_KEY=${BIOMNI_JWT_SECRET}
JWT_ALGORITHM=HS512
DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@127.0.0.1:3306/biomni
USE_MOCK_AGENT=false
AGENT_DATA_PATH=/opt/biomni/data
AGENT_UPLOAD_DATA_PATH=/opt/biomni/upload
CORS_ORIGINS=["http://127.0.0.1","http://${PUBLIC_IP}"]
SPRING_BOOT_URL=http://127.0.0.1:9999
ENVEOF

chown biomni:biomni ${CONFIG_DIR}/biomni.env
chmod 600 ${CONFIG_DIR}/biomni.env

echo "  Config files written."

# ------------------------------------------
# 3. Start MySQL + Redis (docker-compose)
# ------------------------------------------
echo "[3/5] Starting MySQL + Redis via docker-compose..."

cd ${DOCKER_DIR}
docker compose up -d

echo "  Waiting for MySQL to be ready..."
for i in $(seq 1 30); do
    if docker exec mysql57 mysqladmin ping -h localhost --silent 2>/dev/null; then
        echo "  MySQL is ready."
        break
    fi
    if [ "$i" = "30" ]; then
        echo "  ERROR: MySQL failed to start within 60 seconds."
        exit 1
    fi
    sleep 2
done

sleep 5

# ------------------------------------------
# 4. Start Nginx + Spring Boot + Agent
# ------------------------------------------
echo "[4/5] Starting services..."

sudo ln -sf /etc/nginx/sites-available/biomni /etc/nginx/sites-enabled/biomni
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl restart nginx

sudo systemctl enable biomni-admin biomni-agent
sudo systemctl start biomni-admin
sleep 5
sudo systemctl start biomni-agent

# ------------------------------------------
# 5. Save credentials
# ------------------------------------------
echo "[5/5] Saving credentials..."

cat > ${CRED_FILE} <<CREDEOF
============================================================
  Biomni Installation Credentials
  Generated: $(date)
  Instance:  ${INSTANCE_ID}
============================================================

  Admin Portal:   http://${PUBLIC_IP}/admin/
  Client Portal:  http://${PUBLIC_IP}/

  Admin Username: admin
  Admin Email:    admin@biomni.com
  Admin Password: biomni123

  MySQL Root Password: ${MYSQL_ROOT_PASSWORD}
  JWT Secret:          ${BIOMNI_JWT_SECRET}

  IMPORTANT:
    1. Please change the default admin password immediately
    2. Configure LLM API Key in Admin > System Config
    3. Consider binding an Elastic IP
    4. Consider configuring HTTPS (Let's Encrypt)

============================================================
CREDEOF

chmod 600 ${CRED_FILE}
chown ubuntu:ubuntu ${CRED_FILE}

touch ${LOCK_FILE}

echo ""
echo "=========================================="
echo "  Biomni initialization completed!"
echo "  Credentials: ${CRED_FILE}"
echo "=========================================="
