#!/bin/bash
# ============================================================
# Biomni First Boot Initialization Script
# MySQL/Redis 通过 docker-compose 启动
# Spring Boot / Agent 通过 systemd 启动
# ============================================================

set -euo pipefail

LOCK_FILE="/opt/biomni/.initialized"
LOG_FILE="/opt/biomni/logs/first-boot.log"
CONFIG_DIR="/opt/biomni/config"
DOCKER_DIR="/opt/biomni/docker"
CRED_FILE="/home/ubuntu/biomni-credentials.txt"

# 幂等：已初始化则跳过
if [ -f "$LOCK_FILE" ]; then
    echo "Biomni already initialized. Skipping."
    exit 0
fi

mkdir -p /opt/biomni/logs
exec > >(tee -a "$LOG_FILE") 2>&1
echo "=========================================="
echo "Biomni First Boot — $(date)"
echo "=========================================="

# ------------------------------------------
# 1. 生成随机密码和密钥
# ------------------------------------------
echo "[1/6] Generating secrets..."

MYSQL_ROOT_PASSWORD="$(openssl rand -hex 24)"
BIOMNI_JWT_SECRET="$(openssl rand -hex 32)"
ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '=+/')"

# IMDSv2 获取实例信息
TOKEN=$(curl -sf -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 300" --connect-timeout 3 || echo "")
if [ -n "$TOKEN" ]; then
    INSTANCE_ID=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
      http://169.254.169.254/latest/meta-data/instance-id || echo "unknown")
    PUBLIC_IP=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" \
      http://169.254.169.254/latest/meta-data/public-ipv4 || echo "127.0.0.1")
else
    INSTANCE_ID="unknown"
    PUBLIC_IP="127.0.0.1"
fi

echo "  Instance: $INSTANCE_ID | Public IP: $PUBLIC_IP"

# ------------------------------------------
# 2. 写入配置文件
# ------------------------------------------
echo "[2/6] Writing config files..."

# docker-compose .env（MySQL 读取）
cat > ${DOCKER_DIR}/.env <<EOF
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
EOF
chmod 600 ${DOCKER_DIR}/.env

# biomni.env（Spring Boot + Agent 共享）
cat > ${CONFIG_DIR}/biomni.env <<EOF
# Generated by first-boot.sh at $(date)

# ---- Spring Boot env override ----
SPRING_PROFILES_ACTIVE=ami
SERVER_PORT=9999
SPRING_DATASOURCE_MYSQL_JDBC_URL=jdbc:mysql://127.0.0.1:3306/biomni?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
SPRING_DATASOURCE_MYSQL_USERNAME=root
SPRING_DATASOURCE_MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
SPRING_DATASOURCE_MYSQL_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
JWT_SECRET=${BIOMNI_JWT_SECRET}
JWT_EXPIRATION=86400000
SPRING_DATA_REDIS_HOST=127.0.0.1
SPRING_DATA_REDIS_PORT=6379

# ---- Agent env ----
JWT_SECRET_KEY=${BIOMNI_JWT_SECRET}
JWT_ALGORITHM=HS512
DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@127.0.0.1:3306/biomni
USE_MOCK_AGENT=false
AGENT_DATA_PATH=/opt/biomni/data
AGENT_UPLOAD_DATA_PATH=/opt/biomni/upload
CORS_ORIGINS=["http://127.0.0.1","http://${PUBLIC_IP}"]
SPRING_BOOT_URL=http://127.0.0.1:9999
EOF

chown biomni:biomni ${CONFIG_DIR}/biomni.env
chmod 600 ${CONFIG_DIR}/biomni.env

echo "  Config files written."

# ------------------------------------------
# 3. 启动 MySQL + Redis（docker-compose）
# ------------------------------------------
echo "[3/6] Starting MySQL + Redis via docker-compose..."

cd ${DOCKER_DIR}
docker compose up -d

# 等待 MySQL 就绪
echo "  Waiting for MySQL to be ready..."
for i in $(seq 1 30); do
    if docker exec mysql57 mysqladmin ping -h localhost --silent 2>/dev/null; then
        echo "  MySQL is ready."
        break
    fi
    if [ "$i" = "30" ]; then
        echo "  ERROR: MySQL failed to start within 60 seconds."
        exit 1
    fi
    sleep 2
done

# ------------------------------------------
# 4. 随机化管理员密码
# ------------------------------------------
echo "[4/6] Randomizing admin password..."

# init.sql 已经通过 docker-entrypoint-initdb.d 自动执行了
# 现在用随机密码覆盖默认管理员密码 + 强制改密
ADMIN_BCRYPT="$(htpasswd -bnBC 10 "" "${ADMIN_PASSWORD}" | tr -d ':\n')"
docker exec mysql57 mysql -u root -p"${MYSQL_ROOT_PASSWORD}" biomni -e \
  "UPDATE admin SET password='${ADMIN_BCRYPT}', force_password_change=1 WHERE id=1;"

echo "  Admin password randomized."

# ------------------------------------------
# 5. 启动 Nginx + Spring Boot + Agent
# ------------------------------------------
echo "[5/6] Starting services..."

sudo ln -sf /etc/nginx/sites-available/biomni /etc/nginx/sites-enabled/biomni
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl restart nginx

sudo systemctl enable biomni-admin biomni-agent
sudo systemctl start biomni-admin
sleep 5
sudo systemctl start biomni-agent

# ------------------------------------------
# 6. 输出凭据
# ------------------------------------------
echo "[6/6] Saving credentials..."

cat > ${CRED_FILE} <<EOF
============================================================
  Biomni Installation Credentials
  Generated: $(date)
  Instance:  ${INSTANCE_ID}
============================================================

  Admin Portal:   http://${PUBLIC_IP}/admin/
  Client Portal:  http://${PUBLIC_IP}/

  Admin Username: admin
  Admin Email:    admin@biomni.com
  Admin Password: ${ADMIN_PASSWORD}

  MySQL Root Password: ${MYSQL_ROOT_PASSWORD}
  JWT Secret:          ${BIOMNI_JWT_SECRET}

  IMPORTANT:
    1. 请立即登录管理后台修改默认密码
    2. 在管理后台 > 系统配置 中设置 LLM API Key
    3. 建议绑定 Elastic IP 获得固定访问地址
    4. 建议配置 HTTPS (Let's Encrypt)

============================================================
EOF

chmod 600 ${CRED_FILE}
chown ubuntu:ubuntu ${CRED_FILE}

touch ${LOCK_FILE}

echo ""
echo "=========================================="
echo "  ✅ Biomni initialization completed!"
echo "  📄 Credentials: ${CRED_FILE}"
echo "=========================================="
