package com.qusu.mybiomni.dao.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class ConversationDO extends BaseDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.message_count
     *
     * @mbg.generated
     */
    private Integer messageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.total_tokens
     *
     * @mbg.generated
     */
    private Integer totalTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.total_duration_ms
     *
     * @mbg.generated
     */
    private Integer totalDurationMs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.last_message_at
     *
     * @mbg.generated
     */
    private Date lastMessageAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversations.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conversations
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.id
     *
     * @return the value of conversations.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.id
     *
     * @param id the value for conversations.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.user_id
     *
     * @return the value of conversations.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.user_id
     *
     * @param userId the value for conversations.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.title
     *
     * @return the value of conversations.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.title
     *
     * @param title the value for conversations.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.status
     *
     * @return the value of conversations.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.status
     *
     * @param status the value for conversations.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.message_count
     *
     * @return the value of conversations.message_count
     *
     * @mbg.generated
     */
    public Integer getMessageCount() {
        return messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.message_count
     *
     * @param messageCount the value for conversations.message_count
     *
     * @mbg.generated
     */
    public void setMessageCount(Integer messageCount) {
        this.messageCount = messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.total_tokens
     *
     * @return the value of conversations.total_tokens
     *
     * @mbg.generated
     */
    public Integer getTotalTokens() {
        return totalTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.total_tokens
     *
     * @param totalTokens the value for conversations.total_tokens
     *
     * @mbg.generated
     */
    public void setTotalTokens(Integer totalTokens) {
        this.totalTokens = totalTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.total_duration_ms
     *
     * @return the value of conversations.total_duration_ms
     *
     * @mbg.generated
     */
    public Integer getTotalDurationMs() {
        return totalDurationMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.total_duration_ms
     *
     * @param totalDurationMs the value for conversations.total_duration_ms
     *
     * @mbg.generated
     */
    public void setTotalDurationMs(Integer totalDurationMs) {
        this.totalDurationMs = totalDurationMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.last_message_at
     *
     * @return the value of conversations.last_message_at
     *
     * @mbg.generated
     */
    public Date getLastMessageAt() {
        return lastMessageAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.last_message_at
     *
     * @param lastMessageAt the value for conversations.last_message_at
     *
     * @mbg.generated
     */
    public void setLastMessageAt(Date lastMessageAt) {
        this.lastMessageAt = lastMessageAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.created_at
     *
     * @return the value of conversations.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.created_at
     *
     * @param createdAt the value for conversations.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.updated_at
     *
     * @return the value of conversations.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.updated_at
     *
     * @param updatedAt the value for conversations.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversations.deleted_at
     *
     * @return the value of conversations.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversations.deleted_at
     *
     * @param deletedAt the value for conversations.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", title=").append(title);
        sb.append(", status=").append(status);
        sb.append(", messageCount=").append(messageCount);
        sb.append(", totalTokens=").append(totalTokens);
        sb.append(", totalDurationMs=").append(totalDurationMs);
        sb.append(", lastMessageAt=").append(lastMessageAt);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}