package com.qusu.mybiomni.dao.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class ExecutionStepDO extends BaseDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.conversation_id
     *
     * @mbg.generated
     */
    private Integer conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.message_id
     *
     * @mbg.generated
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.step_order
     *
     * @mbg.generated
     */
    private Integer stepOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.step_type
     *
     * @mbg.generated
     */
    private String stepType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.step_name
     *
     * @mbg.generated
     */
    private String stepName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.tool_name
     *
     * @mbg.generated
     */
    private String toolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.tool_input
     *
     * @mbg.generated
     */
    private String toolInput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.tool_output
     *
     * @mbg.generated
     */
    private String toolOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.duration_ms
     *
     * @mbg.generated
     */
    private Integer durationMs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.started_at
     *
     * @mbg.generated
     */
    private Date startedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.completed_at
     *
     * @mbg.generated
     */
    private Date completedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_steps.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.id
     *
     * @return the value of execution_steps.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.id
     *
     * @param id the value for execution_steps.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.conversation_id
     *
     * @return the value of execution_steps.conversation_id
     *
     * @mbg.generated
     */
    public Integer getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.conversation_id
     *
     * @param conversationId the value for execution_steps.conversation_id
     *
     * @mbg.generated
     */
    public void setConversationId(Integer conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.message_id
     *
     * @return the value of execution_steps.message_id
     *
     * @mbg.generated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.message_id
     *
     * @param messageId the value for execution_steps.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.step_order
     *
     * @return the value of execution_steps.step_order
     *
     * @mbg.generated
     */
    public Integer getStepOrder() {
        return stepOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.step_order
     *
     * @param stepOrder the value for execution_steps.step_order
     *
     * @mbg.generated
     */
    public void setStepOrder(Integer stepOrder) {
        this.stepOrder = stepOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.step_type
     *
     * @return the value of execution_steps.step_type
     *
     * @mbg.generated
     */
    public String getStepType() {
        return stepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.step_type
     *
     * @param stepType the value for execution_steps.step_type
     *
     * @mbg.generated
     */
    public void setStepType(String stepType) {
        this.stepType = stepType == null ? null : stepType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.step_name
     *
     * @return the value of execution_steps.step_name
     *
     * @mbg.generated
     */
    public String getStepName() {
        return stepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.step_name
     *
     * @param stepName the value for execution_steps.step_name
     *
     * @mbg.generated
     */
    public void setStepName(String stepName) {
        this.stepName = stepName == null ? null : stepName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.tool_name
     *
     * @return the value of execution_steps.tool_name
     *
     * @mbg.generated
     */
    public String getToolName() {
        return toolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.tool_name
     *
     * @param toolName the value for execution_steps.tool_name
     *
     * @mbg.generated
     */
    public void setToolName(String toolName) {
        this.toolName = toolName == null ? null : toolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.tool_input
     *
     * @return the value of execution_steps.tool_input
     *
     * @mbg.generated
     */
    public String getToolInput() {
        return toolInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.tool_input
     *
     * @param toolInput the value for execution_steps.tool_input
     *
     * @mbg.generated
     */
    public void setToolInput(String toolInput) {
        this.toolInput = toolInput == null ? null : toolInput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.tool_output
     *
     * @return the value of execution_steps.tool_output
     *
     * @mbg.generated
     */
    public String getToolOutput() {
        return toolOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.tool_output
     *
     * @param toolOutput the value for execution_steps.tool_output
     *
     * @mbg.generated
     */
    public void setToolOutput(String toolOutput) {
        this.toolOutput = toolOutput == null ? null : toolOutput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.status
     *
     * @return the value of execution_steps.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.status
     *
     * @param status the value for execution_steps.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.error_message
     *
     * @return the value of execution_steps.error_message
     *
     * @mbg.generated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.error_message
     *
     * @param errorMessage the value for execution_steps.error_message
     *
     * @mbg.generated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.duration_ms
     *
     * @return the value of execution_steps.duration_ms
     *
     * @mbg.generated
     */
    public Integer getDurationMs() {
        return durationMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.duration_ms
     *
     * @param durationMs the value for execution_steps.duration_ms
     *
     * @mbg.generated
     */
    public void setDurationMs(Integer durationMs) {
        this.durationMs = durationMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.started_at
     *
     * @return the value of execution_steps.started_at
     *
     * @mbg.generated
     */
    public Date getStartedAt() {
        return startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.started_at
     *
     * @param startedAt the value for execution_steps.started_at
     *
     * @mbg.generated
     */
    public void setStartedAt(Date startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.completed_at
     *
     * @return the value of execution_steps.completed_at
     *
     * @mbg.generated
     */
    public Date getCompletedAt() {
        return completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.completed_at
     *
     * @param completedAt the value for execution_steps.completed_at
     *
     * @mbg.generated
     */
    public void setCompletedAt(Date completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_steps.created_at
     *
     * @return the value of execution_steps.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_steps.created_at
     *
     * @param createdAt the value for execution_steps.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", conversationId=").append(conversationId);
        sb.append(", messageId=").append(messageId);
        sb.append(", stepOrder=").append(stepOrder);
        sb.append(", stepType=").append(stepType);
        sb.append(", stepName=").append(stepName);
        sb.append(", toolName=").append(toolName);
        sb.append(", toolInput=").append(toolInput);
        sb.append(", toolOutput=").append(toolOutput);
        sb.append(", status=").append(status);
        sb.append(", errorMessage=").append(errorMessage);
        sb.append(", durationMs=").append(durationMs);
        sb.append(", startedAt=").append(startedAt);
        sb.append(", completedAt=").append(completedAt);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}