package com.qusu.mybiomni.dao.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class MessageDO extends BaseDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.conversation_id
     *
     * @mbg.generated
     */
    private Integer conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.content_type
     *
     * @mbg.generated
     */
    private String contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.tokens
     *
     * @mbg.generated
     */
    private Integer tokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.input_tokens
     *
     * @mbg.generated
     */
    private Integer inputTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.output_tokens
     *
     * @mbg.generated
     */
    private Integer outputTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messages
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.id
     *
     * @return the value of messages.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.id
     *
     * @param id the value for messages.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.conversation_id
     *
     * @return the value of messages.conversation_id
     *
     * @mbg.generated
     */
    public Integer getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.conversation_id
     *
     * @param conversationId the value for messages.conversation_id
     *
     * @mbg.generated
     */
    public void setConversationId(Integer conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.role
     *
     * @return the value of messages.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.role
     *
     * @param role the value for messages.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.content
     *
     * @return the value of messages.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.content
     *
     * @param content the value for messages.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.content_type
     *
     * @return the value of messages.content_type
     *
     * @mbg.generated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.content_type
     *
     * @param contentType the value for messages.content_type
     *
     * @mbg.generated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.tokens
     *
     * @return the value of messages.tokens
     *
     * @mbg.generated
     */
    public Integer getTokens() {
        return tokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.tokens
     *
     * @param tokens the value for messages.tokens
     *
     * @mbg.generated
     */
    public void setTokens(Integer tokens) {
        this.tokens = tokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.input_tokens
     *
     * @return the value of messages.input_tokens
     *
     * @mbg.generated
     */
    public Integer getInputTokens() {
        return inputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.input_tokens
     *
     * @param inputTokens the value for messages.input_tokens
     *
     * @mbg.generated
     */
    public void setInputTokens(Integer inputTokens) {
        this.inputTokens = inputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.output_tokens
     *
     * @return the value of messages.output_tokens
     *
     * @mbg.generated
     */
    public Integer getOutputTokens() {
        return outputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.output_tokens
     *
     * @param outputTokens the value for messages.output_tokens
     *
     * @mbg.generated
     */
    public void setOutputTokens(Integer outputTokens) {
        this.outputTokens = outputTokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.created_at
     *
     * @return the value of messages.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.created_at
     *
     * @param createdAt the value for messages.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", conversationId=").append(conversationId);
        sb.append(", role=").append(role);
        sb.append(", content=").append(content);
        sb.append(", contentType=").append(contentType);
        sb.append(", tokens=").append(tokens);
        sb.append(", inputTokens=").append(inputTokens);
        sb.append(", outputTokens=").append(outputTokens);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}