package com.qusu.mybiomni.dao.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class SystemConfigDO extends BaseDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_key
     *
     * @mbg.generated
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_value
     *
     * @mbg.generated
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_type
     *
     * @mbg.generated
     */
    private String configType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.is_sensitive
     *
     * @mbg.generated
     */
    private Integer isSensitive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_key
     *
     * @return the value of system_config.config_key
     *
     * @mbg.generated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_key
     *
     * @param configKey the value for system_config.config_key
     *
     * @mbg.generated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_value
     *
     * @return the value of system_config.config_value
     *
     * @mbg.generated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_value
     *
     * @param configValue the value for system_config.config_value
     *
     * @mbg.generated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_type
     *
     * @return the value of system_config.config_type
     *
     * @mbg.generated
     */
    public String getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_type
     *
     * @param configType the value for system_config.config_type
     *
     * @mbg.generated
     */
    public void setConfigType(String configType) {
        this.configType = configType == null ? null : configType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.description
     *
     * @return the value of system_config.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.description
     *
     * @param description the value for system_config.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.is_sensitive
     *
     * @return the value of system_config.is_sensitive
     *
     * @mbg.generated
     */
    public Integer getIsSensitive() {
        return isSensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.is_sensitive
     *
     * @param isSensitive the value for system_config.is_sensitive
     *
     * @mbg.generated
     */
    public void setIsSensitive(Integer isSensitive) {
        this.isSensitive = isSensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.created_at
     *
     * @return the value of system_config.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.created_at
     *
     * @param createdAt the value for system_config.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.updated_at
     *
     * @return the value of system_config.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.updated_at
     *
     * @param updatedAt the value for system_config.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", configKey=").append(configKey);
        sb.append(", configValue=").append(configValue);
        sb.append(", configType=").append(configType);
        sb.append(", description=").append(description);
        sb.append(", isSensitive=").append(isSensitive);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}