package com.qusu.mybiomni.dao.mysql.model;

import java.io.Serializable;
import java.util.Date;

public class UserQuotaDO extends BaseDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quotas.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quotas.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quotas.total_token_limit
     *
     * @mbg.generated
     */
    private Integer totalTokenLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quotas.total_token_used
     *
     * @mbg.generated
     */
    private Integer totalTokenUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quotas.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quotas.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quotas.id
     *
     * @return the value of user_quotas.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quotas.id
     *
     * @param id the value for user_quotas.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quotas.user_id
     *
     * @return the value of user_quotas.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quotas.user_id
     *
     * @param userId the value for user_quotas.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quotas.total_token_limit
     *
     * @return the value of user_quotas.total_token_limit
     *
     * @mbg.generated
     */
    public Integer getTotalTokenLimit() {
        return totalTokenLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quotas.total_token_limit
     *
     * @param totalTokenLimit the value for user_quotas.total_token_limit
     *
     * @mbg.generated
     */
    public void setTotalTokenLimit(Integer totalTokenLimit) {
        this.totalTokenLimit = totalTokenLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quotas.total_token_used
     *
     * @return the value of user_quotas.total_token_used
     *
     * @mbg.generated
     */
    public Integer getTotalTokenUsed() {
        return totalTokenUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quotas.total_token_used
     *
     * @param totalTokenUsed the value for user_quotas.total_token_used
     *
     * @mbg.generated
     */
    public void setTotalTokenUsed(Integer totalTokenUsed) {
        this.totalTokenUsed = totalTokenUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quotas.created_at
     *
     * @return the value of user_quotas.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quotas.created_at
     *
     * @param createdAt the value for user_quotas.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quotas.updated_at
     *
     * @return the value of user_quotas.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quotas.updated_at
     *
     * @param updatedAt the value for user_quotas.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", totalTokenLimit=").append(totalTokenLimit);
        sb.append(", totalTokenUsed=").append(totalTokenUsed);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}