package com.qusu.mybiomni.dao.mysql.dao;

import com.qusu.mybiomni.dao.mysql.model.ConversationDO;
import com.qusu.mybiomni.dao.mysql.model.ConversationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConversationDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    long countByExample(ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int deleteByExample(ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int insert(ConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int insertSelective(ConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    List<ConversationDO> selectByExampleWithRowbounds(ConversationDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    List<ConversationDO> selectByExample(ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    ConversationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConversationDO record, @Param("example") ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConversationDO record, @Param("example") ConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConversationDO record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table conversations
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<ConversationDO> list);
}