package com.qusu.mybiomni.dao.mysql.dao;

import com.qusu.mybiomni.dao.mysql.model.ExecutionStepDO;
import com.qusu.mybiomni.dao.mysql.model.ExecutionStepDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ExecutionStepDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    long countByExample(ExecutionStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int deleteByExample(ExecutionStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int insert(ExecutionStepDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int insertSelective(ExecutionStepDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    List<ExecutionStepDO> selectByExampleWithRowbounds(ExecutionStepDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    List<ExecutionStepDO> selectByExample(ExecutionStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    ExecutionStepDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExecutionStepDO record, @Param("example") ExecutionStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExecutionStepDO record, @Param("example") ExecutionStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExecutionStepDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExecutionStepDO record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table execution_steps
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<ExecutionStepDO> list);
}