package com.qusu.mybiomni.dao.mysql.dao;

import com.qusu.mybiomni.dao.mysql.model.SystemConfigDO;
import com.qusu.mybiomni.dao.mysql.model.SystemConfigDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SystemConfigDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    long countByExample(SystemConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int deleteByExample(SystemConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int insert(SystemConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int insertSelective(SystemConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    List<SystemConfigDO> selectByExampleWithRowbounds(SystemConfigDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    List<SystemConfigDO> selectByExample(SystemConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    SystemConfigDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemConfigDO record, @Param("example") SystemConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemConfigDO record, @Param("example") SystemConfigDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemConfigDO record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table system_config
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<SystemConfigDO> list);
}