package com.qusu.mybiomni.dao.mysql.dao;

import com.qusu.mybiomni.dao.mysql.model.UserQuotaDO;
import com.qusu.mybiomni.dao.mysql.model.UserQuotaDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserQuotaDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    long countByExample(UserQuotaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int deleteByExample(UserQuotaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int insert(UserQuotaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int insertSelective(UserQuotaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    List<UserQuotaDO> selectByExampleWithRowbounds(UserQuotaDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    List<UserQuotaDO> selectByExample(UserQuotaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    UserQuotaDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserQuotaDO record, @Param("example") UserQuotaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserQuotaDO record, @Param("example") UserQuotaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserQuotaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserQuotaDO record);

    /**
     * 这是Mybatis Generator拓展插件生成的方法(请勿删除).
     * This method corresponds to the database table user_quotas
     *
     * @mbg.generated
     * @author hewei
     */
    int batchInsert(@Param("list") List<UserQuotaDO> list);
}